import crypto from "crypto";

// Use an environment variable, fallback to a random 32-byte key for local dev ONLY
const ENCRYPTION_KEY = process.env.ADDRESS_ENCRYPTION_KEY 
  ? Buffer.from(process.env.ADDRESS_ENCRYPTION_KEY, 'hex')
  : crypto.randomBytes(32); // 256-bit key

const ALGORITHM = 'aes-256-gcm';

/**
 * Encrypts a string (e.g., JSON stringified address) securely using AES-256-GCM.
 * Returns a payload containing the IV, Auth Tag, and Encrypted Data.
 */
export function encryptAddress(addressJson: string): string {
  const iv = crypto.randomBytes(12); // 96-bit IV for GCM
  const cipher = crypto.createCipheriv(ALGORITHM, ENCRYPTION_KEY, iv);
  
  let encrypted = cipher.update(addressJson, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  const authTag = cipher.getAuthTag().toString('hex');
  
  // Format: iv:authTag:encryptedData
  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a payload generated by encryptAddress.
 */
export function decryptAddress(encryptedPayload: string): string | null {
  try {
    const parts = encryptedPayload.split(':');
    if (parts.length !== 3) return null;
    
    const [ivHex, authTagHex, encryptedHex] = parts;
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    
    const decipher = crypto.createDecipheriv(ALGORITHM, ENCRYPTION_KEY, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (error) {
    console.error("[encryption] Failed to decrypt address data");
    return null; // Do not log the actual error for security
  }
}
